version: "3"
services:
    pg-accounts:
        image: postgres:13-buster
        restart: always
        environment:
            POSTGRES_PASSWORD: secret123
            POSTGRES_USER: accounts
            POSTGRES_HOST_AUTH_METHOD: md5
        volumes:
            - pg-accounts:/var/lib/postgresql/data
    accounts:
        image: ghcr.io/vicr123/vicr123-accounts:master
        depends_on: [pg-accounts]
        restart: always
        environment:
            ACCOUNTS_DB_HOSTNAME: pg-accounts
            ACCOUNTS_DB_USERNAME: accounts
            ACCOUNTS_DB_DATABASE: accounts
            ACCOUNTS_DB_PASSWORD: secret123
        volumes:
            - "/var/parlance/vicr123-accounts:/var/vicr123-accounts"
    pg-parlance:
        image: postgres:13-buster
        restart: always
        environment:
            POSTGRES_PASSWORD: secret123
            POSTGRES_USER: parlance
            POSTGRES_HOST_AUTH_METHOD: md5
        volumes:
            - pg-parlance:/var/lib/postgresql/data
    parlance:
        image: ghcr.io/vicr123/parlance:main
        depends_on: [accounts, pg-parlance]
        restart: always
        environment:
            Parlance__DatabaseConnectionString: "Host=pg-parlance; Database=parlance; Username=parlance; Password=secret123;"
            Parlance__RepositoryDirectory: "/Data"
            ASPNETCORE_URLS: "http://0.0.0.0:5000/"
        volumes:
            - "/var/parlance/vicr123-accounts:/var/vicr123-accounts"
            - "parlance-home:/root"
            - "parlance-data:/Data"
        ports:
            - "5000:5000"
volumes:
    pg-accounts:
    pg-parlance:
    parlance-home:
    parlance-data:
