version: "3"
services:
    pg-parlance:
        image: postgres:13-buster
        restart: always
        environment:
            POSTGRES_PASSWORD: secret123
            POSTGRES_USER: parlance
            POSTGRES_HOST_AUTH_METHOD: md5
        volumes:
            - pg-parlance:/var/lib/postgresql/data
    parlance:
        image: ghcr.io/vicr123/parlance:main
        depends_on: [pg-parlance]
        restart: always
        environment:
            Parlance__DatabaseConnectionString: "Host=pg-parlance; Database=parlance; Username=parlance; Password=secret123;"
            Parlance__RepositoryDirectory: "/Data"
            ASPNETCORE_URLS: "http://0.0.0.0:5000/"
        volumes:
            - "/var/vicr123-accounts:/var/vicr123-accounts"
            - "parlance-home:/root"
            - "parlance-data:/Data"
        ports:
            - "4000:5000"
volumes:
    pg-parlance:
    parlance-home:
    parlance-data:
