version: "3"
services:
    pg-accounts:
        image: postgres:13-buster
        restart: always
        environment:
            POSTGRES_PASSWORD: secret123
            POSTGRES_USER: accounts
            POSTGRES_HOST_AUTH_METHOD: md5
        volumes:
            - pg-accounts:/var/lib/postgresql/data
    accounts:
        image: ghcr.io/vicr123/vicr123-accounts:master
        depends_on: [pg-accounts]
        restart: always
        environment:
            ACCOUNTS_DB_HOSTNAME: pg-accounts
            ACCOUNTS_DB_USERNAME: accounts
            ACCOUNTS_DB_DATABASE: accounts
            ACCOUNTS_DB_PASSWORD: secret123
        volumes:
            - "/var/entertaining/vicr123-accounts:/var/vicr123-accounts"
    pg-entertaining:
        image: postgres:13-buster
        restart: always
        environment:
            POSTGRES_PASSWORD: secret123
            POSTGRES_USER: entertaining
            POSTGRES_HOST_AUTH_METHOD: md5
        volumes:
            - pg-entertaining:/var/lib/postgresql/data
    entertaining:
        image: ghcr.io/vicr123/entertaining-server:master
        depends_on: [accounts, pg-entertaining]
        restart: always
        environment:
            DATABASE_HOST: pg-entertaining
            DATABASE_USER: entertaining
            DATABASE_PASSWORD: secret123
            DATABASE_DATABASE: entertaining
            REPORTSLOCATION: /reports
        volumes:
            - "/var/entertaining/vicr123-accounts:/var/vicr123-accounts"
            - "/var/lib/entertaining-games/reports:/reports"
            - "/var/lib/entertaining-games/documents:/usr/src/app/documents"
        ports:
            - "3000:3000"
volumes:
    pg-accounts:
    pg-entertaining: